Web/Controllers/LaptopStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class LaptopStoreController : Controller
    {
        dbQLBanLaptopDataContext data = new dbQLBanLaptopDataContext();
        private List<DanhMuc> Laylaptopmoi(int count)
        {
            return data.DanhMucs.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        // GET: LaptopStore
        public ActionResult Index()
        {
            var laptopmoi = Laylaptopmoi(100);
            return View(laptopmoi);
        }

        public ActionResult ACER()
        {
            string Chuoi = "";
            var product = (from p in data.DanhMucs where p.Hang == "ACER" select p).Take(100).ToList();
            for (int i = 0; i < product.Count; i++)
            {
                Chuoi += "<div class=\"item-pro-home\">";
                Chuoi += "<div class=\"box-img-pro-home\">";
                Chuoi += "<img src = \"" + product[i].Image + "\" />";
                Chuoi += "</div>";
                Chuoi += "<a href=\"#\">" + product[i].TenSanPham + "</a>";
                Chuoi += "<p>Giá: " + product[i].GiaTien + "</p>";
                Chuoi += "</div>";
            }
            ViewBag.ACER = Chuoi;
            return View(product);
        }

        public ActionResult ASUS()
        {
            string Chuoi = "";
            var product = (from p in data.DanhMucs where p.Hang == "ASUS" select p).Take(100).ToList();
            for (int i = 0; i < product.Count; i++)
            {
                Chuoi += "<div class=\"item-pro-home\">";
                Chuoi += "<div class=\"box-img-pro-home\">";
                Chuoi += "<img src = \"" + product[i].Image + "\" />";
                Chuoi += "</div>";
                Chuoi += "<a href=\"#\">" + product[i].TenSanPham + "</a>";
                Chuoi += "<p>Giá: " + product[i].GiaTien + "</p>";
                Chuoi += "</div>";
            }
            ViewBag.ASUS = Chuoi;
            return View(product);
        }

        public ActionResult DELL()
        {
            string Chuoi = "";
            var product = (from p in data.DanhMucs where p.Hang == "DELL" select p).Take(100).ToList();
            for (int i = 0; i < product.Count; i++)
            {
                Chuoi += "<div class=\"item-pro-home\">";
                Chuoi += "<div class=\"box-img-pro-home\">";
                Chuoi += "<img src = \"" + product[i].Image + "\" />";
                Chuoi += "</div>";
                Chuoi += "<a href=\"#\">" + product[i].TenSanPham + "</a>";
                Chuoi += "<p>Giá: " + product[i].GiaTien + "</p>";
                Chuoi += "</div>";
            }
            ViewBag.DELL = Chuoi;
            return View(product);
        }

        public ActionResult MAC()
        {
            string Chuoi = "";
            var product = (from p in data.DanhMucs where p.Hang == "MAC" select p).Take(100).ToList();
            for (int i = 0; i < product.Count; i++)
            {
                Chuoi += "<div class=\"item-pro-home\">";
                Chuoi += "<div class=\"box-img-pro-home\">";
                Chuoi += "<img src = \"" + product[i].Image + "\" />";
                Chuoi += "</div>";
                Chuoi += "<a href=\"#\">" + product[i].TenSanPham + "</a>";
                Chuoi += "<p>Giá: " + product[i].GiaTien + "</p>";
                Chuoi += "</div>";
            }
            ViewBag.MAC = Chuoi;
            return View(product);
        }

        public ActionResult Detail(int id)
        {
            var laptop = from l in data.DanhMucs
                         where l.ID == id
                         select l;
            return View(laptop.Single());
        }
    }
}

Web/Views/LaptopStore/ACER.cshtml
@{
    ViewBag.Title = "ACER";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<link href="~/Content/Style.css" rel="stylesheet " />
@Html.Raw(ViewBag.ACER)

Web/Views/LaptopStore/ASUS.cshtml
@{
    ViewBag.Title = "ASUS";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<link href="~/Content/Style.css" rel="stylesheet " />
@Html.Raw(ViewBag.ASUS)

Web/Views/LaptopStore/DELL.cshtml
@{
    ViewBag.Title = "DELL";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<link href="~/Content/Style.css" rel="stylesheet " />
@Html.Raw(ViewBag.DELL)

Web/Views/LaptopStore/Detail.cshtml
<style type="text/css">
    #Datmua a {
        clear: both;
        background-color: red;
        color: white;
        width: 120px;
        height: 35px;
        display: block;
        float: right;
        text-align: center;
        padding-top: 10px;
        text-decoration: none;
        font-weight: bold;
    }

        #Datmua a:hover {
            background-color: gray;
            color: red;
        }
</style>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3> THÔNG TIN CHI TIẾT SẢN PHẨM</h3>
<div>
    <div style="width:40%; float:left; border-left: dotted 1px; border-color:azure">
        <img src="@Model.Image" width="50%" />
    </div>
    <div style="width:60%; float:left; padding:10px">
        <h4 style="font-weight:bold; color:red">Tên sản phẩm: @Model.TenSanPham </h4>
        <p style="text-align:justify"><Span style="font-weight:bold"> Mô tả: </Span>@Model.Description </p>
        <p style="font-weight:bold"> Giá bán: <span style="color:red; font-size:16pt "> @String.Format("{0:0,0}", Model.GiaTien) VNĐ </span></p>
    </div>
    <div>
        <div id="Datmua">
            <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMasanpham = @Model.ID, @strURL=Request.Url.ToString() })" class="list-group-item">
                ĐẶT MUA
            </a>
        </div>
    </div>
</div>

Web/Views/LaptopStore/Index.cshtml
@model IEnumerable<Web.Models.DanhMuc>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="row">
@foreach (var laptop in Model)
{
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <a href="@Url.Action("Detail","LaptopStore", new { id = laptop.ID})">
                <img alt="@laptop.TenSanPham" src="@laptop.Image" width="200" />

                <div>
                    <br />
                    <h6 style="text-align: left">
                        @laptop.TenSanPham
                    </h6>
                    <h4 style="text-align: left; color: red">
                        @laptop.GiaTien VNĐ
                    </h4>
                    <p></p>
                </div>
            </a>
        </div>
    </div>     
}

Web/Views/LaptopStore/MAC.cshtml
@{
    ViewBag.Title = "MAC";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<link href="~/Content/Style.css" rel="stylesheet " />
@Html.Raw(ViewBag.MAC)